
import { Category, Venue, CategoryType, Language } from './types';

// Regions and Districts of Uzbekistan
export const REGIONS: Record<string, string[]> = {
  "Toshkent shahri": ["Chilonzor", "Yunusobod", "Mirzo Ulug'bek", "Yakkasaroy", "Sergeli", "Olmazor", "Shayxontohur", "Mirobod", "Uchtepa", "Bektemir"],
  "Toshkent viloyati": ["Chirchiq", "Angren", "Bo'stonliq", "Parkent", "Qibray", "Zangiota"],
  "Samarqand": ["Samarqand sh.", "Urgut", "Jomboy", "Kattaqo'rg'on"],
  "Buxoro": ["Buxoro sh.", "G'ijduvon", "Kogon"],
  "Andijon": ["Andijon sh.", "Asaka", "Xonobod"],
  "Farg'ona": ["Farg'ona sh.", "Qo'qon", "Marg'ilon", "Rishton"],
  "Namangan": ["Namangan sh.", "Chust", "Pop"],
  "Xorazm": ["Urganch", "Xiva", "Hazorasp"],
  "Qashqadaryo": ["Qarshi", "Shahrisabz", "Kitob"],
  "Surxondaryo": ["Termiz", "Denov", "Boysun"],
  "Navoiy": ["Navoiy sh.", "Zarafshon", "Karmana"],
  "Jizzax": ["Jizzax sh.", "Zomin", "Forish"],
  "Sirdaryo": ["Guliston", "Yangiyer", "Sirdaryo"],
  "Qoraqalpog'iston": ["Nukus", "Mo'ynoq", "Qo'ng'irot"]
};

export const CATEGORIES: Category[] = [
  // Team Sports
  { id: 'football', name: 'Futbol (Mini/Stadion)', type: 'TEAM' },
  { id: 'basketball', name: 'Basketbol', type: 'TEAM' },
  { id: 'volleyball', name: 'Voleybol', type: 'TEAM' },
  // Water
  { id: 'swimming', name: 'Suzish Havzasi', type: 'WATER' },
  { id: 'rowing', name: 'Eshkakli Eshish', type: 'WATER' },
  // Combat
  { id: 'boxing', name: 'Boks', type: 'COMBAT' },
  { id: 'judo', name: 'Dzyudo', type: 'COMBAT' },
  { id: 'mma', name: 'MMA', type: 'COMBAT' },
  { id: 'taekwondo', name: 'Taekvondo', type: 'COMBAT' },
  { id: 'kurash', name: 'Milliy Kurash', type: 'COMBAT' },
  // Racket & Golf
  { id: 'tennis', name: 'Tennis', type: 'RACKET' },
  { id: 'table_tennis', name: 'Stol Tennisi', type: 'RACKET' },
  { id: 'badminton', name: 'Badminton', type: 'RACKET' },
  { id: 'golf', name: 'Golf', type: 'RACKET' },
  // Winter
  { id: 'skiing', name: 'Chang\'i', type: 'WINTER' },
  { id: 'skating', name: 'Konkida uchish', type: 'WINTER' },
  // Equestrian
  { id: 'horse_riding', name: 'Ot Sporti', type: 'EQUESTRIAN' },
  // Fitness
  { id: 'gym', name: 'Fitnes & Zal', type: 'FITNESS' },
  { id: 'crossfit', name: 'Crossfit', type: 'FITNESS' },
  // Shooting
  { id: 'archery', name: 'Kamondan otish', type: 'SHOOTING' },
  { id: 'shooting', name: 'Miltiqdan otish', type: 'SHOOTING' },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  uz: {
    home: "Asosiy",
    favorites: "Sevimlilar",
    map: "Xarita",
    profile: "Profil",
    search_placeholder: "Maydon nomi, tuman...",
    all: "Barchasi",
    filter: "Filterlar",
    region: "Hudud",
    district: "Tuman",
    districts: "Tumanlar",
    amenities: "Qulayliklar",
    sport_type: "Sport turi",
    show_results: "Natijalarni ko'rsatish",
    reset: "Tozalash",
    price_per_hour: "Narxi (soatiga)",
    working_hours: "Ish vaqti",
    open: "Ochiq",
    closed: "Yopiq",
    installment: "Bo'lib to'lash",
    full_payment: "To'liq to'lov",
    phone: "Telefon",
    telegram: "Telegram",
    address: "Manzil",
    info: "Ma'lumot",
    reviews: "Izohlar",
    no_reviews: "Hozircha izohlar yo'q",
    added_on: "Platformaga qo'shilgan",
    contact_history: "Bog'lanishlar tarixi",
    review_history: "Izohlar tarixi",
    settings: "Sozlamalar",
    dark_mode: "Tungi rejim",
    light_mode: "Kunduzgi rejim",
    language: "Til",
    notifications: "Bildirishnomalar",
    empty_search: "Hech qanday maydon topilmadi. Filterlarni o'zgartirib ko'ring.",
    empty_favorites: "Sevimlilar ro'yxati bo'sh",
    details: "Batafsil",
    on_map: "Xaritada",
    call: "Qo'ng'iroq",
    share: "Ulashish",
    share_via: "Orqali ulashish",
    copy_link: "Havolani nusxalash",
    link_copied: "Havola nusxalandi!",
    // Amenities
    amenity_prayer: "Namozxona",
    amenity_shower: "Dush (Yuvinish xonasi)",
    amenity_changing: "Kiyinish xonasi",
    amenity_parking: "Avtoturargoh",
    amenity_equipment: "Inventar ijarasi",
    amenity_lighting: "Yoritish tizimi",
    // Filter Labels
    filter_prayer: "Namozxona mavjud",
    filter_shower: "Dush/Yuvinish xonasi",
    filter_equipment: "Inventar ijarasi",
    filter_installment: "Bo'lib to'lash imkoni",
    filter_open: "Hozir ochiq",
    // Categories
    cat_football: "Futbol",
    cat_basketball: "Basketbol",
    cat_volleyball: "Voleybol",
    cat_swimming: "Suzish",
    cat_rowing: "Eshkakli Eshish",
    cat_boxing: "Boks",
    cat_judo: "Dzyudo",
    cat_mma: "MMA",
    cat_taekwondo: "Taekvondo",
    cat_kurash: "Kurash",
    cat_tennis: "Tennis",
    cat_table_tennis: "Stol Tennisi",
    cat_badminton: "Badminton",
    cat_golf: "Golf",
    cat_skiing: "Chang'i",
    cat_skating: "Konki",
    cat_horse_riding: "Ot Sporti",
    cat_gym: "Fitnes & Zal",
    cat_crossfit: "Crossfit",
    cat_archery: "Kamondan otish",
    cat_shooting: "Miltiqdan otish",
  },
  ru: {
    home: "Главная",
    favorites: "Избранное",
    map: "Карта",
    profile: "Профиль",
    search_placeholder: "Название, район...",
    all: "Все",
    filter: "Фильтры",
    region: "Регион",
    district: "Район",
    districts: "Районы",
    amenities: "Удобства",
    sport_type: "Вид спорта",
    show_results: "Показать результаты",
    reset: "Сбросить",
    price_per_hour: "Цена (в час)",
    working_hours: "Рабочее время",
    open: "Открыто",
    closed: "Закрыто",
    installment: "Рассрочка",
    full_payment: "Полная оплата",
    phone: "Телефон",
    telegram: "Telegram",
    address: "Адрес",
    info: "Информация",
    reviews: "Отзывы",
    no_reviews: "Отзывов пока нет",
    added_on: "Добавлено",
    contact_history: "История контактов",
    review_history: "История отзывов",
    settings: "Настройки",
    dark_mode: "Ночной режим",
    light_mode: "Дневной режим",
    language: "Язык",
    notifications: "Уведомления",
    empty_search: "Ничего не найдено. Попробуйте изменить фильтры.",
    empty_favorites: "Список избранного пуст",
    details: "Подробнее",
    on_map: "На карте",
    call: "Вызов",
    share: "Поделиться",
    share_via: "Поделиться через",
    copy_link: "Копировать ссылку",
    link_copied: "Ссылка скопирована!",
    // Amenities
    amenity_prayer: "Молельная комната",
    amenity_shower: "Душ",
    amenity_changing: "Раздевалка",
    amenity_parking: "Парковка",
    amenity_equipment: "Аренда инвентаря",
    amenity_lighting: "Освещение",
    // Filter Labels
    filter_prayer: "Есть молельная",
    filter_shower: "Душ/Ванная",
    filter_equipment: "Аренда инвентаря",
    filter_installment: "Есть рассрочка",
    filter_open: "Сейчас открыто",
    // Categories
    cat_football: "Футбол",
    cat_basketball: "Баскетбол",
    cat_volleyball: "Волейбол",
    cat_swimming: "Плавание",
    cat_rowing: "Гребля",
    cat_boxing: "Бокс",
    cat_judo: "Дзюдо",
    cat_mma: "ММА",
    cat_taekwondo: "Тхэквондо",
    cat_kurash: "Кураш",
    cat_tennis: "Теннис",
    cat_table_tennis: "Настольный теннис",
    cat_badminton: "Бадминтон",
    cat_golf: "Гольф",
    cat_skiing: "Лыжи",
    cat_skating: "Коньки",
    cat_horse_riding: "Конный спорт",
    cat_gym: "Фитнес & Зал",
    cat_crossfit: "Кроссфит",
    cat_archery: "Стрельба из лука",
    cat_shooting: "Стрельба",
  },
  en: {
    home: "Home",
    favorites: "Favorites",
    map: "Map",
    profile: "Profile",
    search_placeholder: "Venue name, district...",
    all: "All",
    filter: "Filters",
    region: "Region",
    district: "District",
    districts: "Districts",
    amenities: "Amenities",
    sport_type: "Sport Type",
    show_results: "Show Results",
    reset: "Reset",
    price_per_hour: "Price (per hour)",
    working_hours: "Working Hours",
    open: "Open",
    closed: "Closed",
    installment: "Installment",
    full_payment: "Full Payment",
    phone: "Phone",
    telegram: "Telegram",
    address: "Address",
    info: "Info",
    reviews: "Reviews",
    no_reviews: "No reviews yet",
    added_on: "Added on",
    contact_history: "Contact History",
    review_history: "Review History",
    settings: "Settings",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    language: "Language",
    notifications: "Notifications",
    empty_search: "No venues found. Try changing filters.",
    empty_favorites: "Favorites list is empty",
    details: "Details",
    on_map: "On Map",
    call: "Call",
    share: "Share",
    share_via: "Share via",
    copy_link: "Copy Link",
    link_copied: "Link Copied!",
    // Amenities
    amenity_prayer: "Prayer Room",
    amenity_shower: "Shower",
    amenity_changing: "Changing Room",
    amenity_parking: "Parking",
    amenity_equipment: "Equipment Rental",
    amenity_lighting: "Lighting",
    // Filter Labels
    filter_prayer: "Prayer Room",
    filter_shower: "Shower",
    filter_equipment: "Equipment Rental",
    filter_installment: "Installment Available",
    filter_open: "Open Now",
    // Categories
    cat_football: "Football",
    cat_basketball: "Basketball",
    cat_volleyball: "Volleyball",
    cat_swimming: "Swimming",
    cat_rowing: "Rowing",
    cat_boxing: "Boxing",
    cat_judo: "Judo",
    cat_mma: "MMA",
    cat_taekwondo: "Taekwondo",
    cat_kurash: "Kurash",
    cat_tennis: "Tennis",
    cat_table_tennis: "Table Tennis",
    cat_badminton: "Badminton",
    cat_golf: "Golf",
    cat_skiing: "Skiing",
    cat_skating: "Skating",
    cat_horse_riding: "Horse Riding",
    cat_gym: "Fitness & Gym",
    cat_crossfit: "Crossfit",
    cat_archery: "Archery",
    cat_shooting: "Shooting",
  }
};

// Color mapping function based on Category Type
export const getCategoryColor = (type: CategoryType, isDark: boolean): string => {
  switch (type) {
    case 'TEAM': return isDark ? 'bg-emerald-900 text-emerald-200 border-emerald-700' : 'bg-emerald-100 text-emerald-800 border-emerald-200';
    case 'WATER': return isDark ? 'bg-sky-900 text-sky-200 border-sky-700' : 'bg-sky-100 text-sky-800 border-sky-200';
    case 'WINTER': return isDark ? 'bg-slate-700 text-slate-200 border-slate-500' : 'bg-slate-100 text-slate-800 border-slate-200';
    case 'COMBAT': return isDark ? 'bg-red-900 text-red-200 border-red-700' : 'bg-red-100 text-red-800 border-red-200';
    case 'EQUESTRIAN': return isDark ? 'bg-amber-900 text-amber-200 border-amber-700' : 'bg-amber-100 text-amber-800 border-amber-200';
    case 'FITNESS': return isDark ? 'bg-violet-900 text-violet-200 border-violet-700' : 'bg-violet-100 text-violet-800 border-violet-200';
    case 'SHOOTING': return isDark ? 'bg-zinc-900 text-zinc-200 border-zinc-700' : 'bg-zinc-200 text-zinc-800 border-zinc-300';
    case 'RACKET': return isDark ? 'bg-lime-900 text-lime-200 border-lime-700' : 'bg-lime-100 text-lime-800 border-lime-200';
    default: return isDark ? 'bg-gray-800 text-gray-200 border-gray-700' : 'bg-gray-100 text-gray-800 border-gray-200';
  }
};

const commonAmenities = {
  parking: true,
  changingRoom: true,
  shower: true,
  prayerRoom: true,
  equipmentRental: true,
  lighting: true
};

export const MOCK_VENUES: Venue[] = [
  // ... (Existing MOCK_VENUES data remains unchanged)
  // --- TEAM SPORTS (Football, Basketball, Volleyball) ---
  {
    id: 't1',
    name: 'Bunyodkor Mini Football',
    description: 'Professional sun\'iy qoplamali mini-futbol maydoni. Do\'stlar bilan o\'ynash uchun ajoyib joy.',
    categories: ['football'],
    images: ['https://loremflickr.com/800/600/stadium?lock=1', 'https://loremflickr.com/800/600/football?lock=2', 'https://loremflickr.com/800/600/soccer?lock=3'],
    rating: 4.8,
    reviewCount: 124,
    location: { lat: 41.2858, lng: 69.2040, region: 'Toshkent shahri', district: 'Chilonzor', address: 'Chilonzor 6-mavze, 12-uy' },
    pricePerHour: 120000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998901234567'], telegram: 'bunyodkor_admin' },
    workingHours: '08:00 - 23:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2023-01-01'
  },
  {
    id: 't2',
    name: 'Paxtakor Training Field',
    description: 'Afsonaviy Paxtakor stadioni yonginasidagi mashg\'ulot maydoni.',
    categories: ['football'],
    images: ['https://loremflickr.com/800/600/stadium?lock=4', 'https://loremflickr.com/800/600/football?lock=5', 'https://loremflickr.com/800/600/grass?lock=6'],
    rating: 4.7,
    reviewCount: 85,
    location: { lat: 41.3111, lng: 69.2401, region: 'Toshkent shahri', district: 'Shayxontohur', address: 'Islom Karimov ko\'chasi' },
    pricePerHour: 150000,
    currency: 'UZS',
    hasInstallment: true,
    amenities: commonAmenities,
    contact: { phone: ['+998712000001'] },
    workingHours: '09:00 - 22:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2023-02-15'
  },
  {
    id: 't3',
    name: 'Samarqand Dinamo Arena',
    description: 'Samarqand shahrining markaziy o\'yingohi, yugurish yo\'laklari bilan.',
    categories: ['football'],
    images: ['https://loremflickr.com/800/600/stadium?lock=7', 'https://loremflickr.com/800/600/football?lock=8', 'https://loremflickr.com/800/600/sport?lock=9'],
    rating: 4.6,
    reviewCount: 200,
    location: { lat: 39.6542, lng: 66.9597, region: 'Samarqand', district: 'Samarqand sh.', address: 'Dahbed ko\'chasi' },
    pricePerHour: 100000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: { ...commonAmenities, shower: true },
    contact: { phone: ['+998662223344'] },
    workingHours: '08:00 - 20:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2022-11-20'
  },
  {
    id: 't4',
    name: 'Humo Arena Basketball',
    description: 'Xalqaro talablarga javob beradigan yopiq basketbol zali.',
    categories: ['basketball'],
    images: ['https://loremflickr.com/800/600/basketball?lock=10', 'https://loremflickr.com/800/600/nba?lock=11', 'https://loremflickr.com/800/600/court?lock=12'],
    rating: 4.9,
    reviewCount: 56,
    location: { lat: 41.3000, lng: 69.2500, region: 'Toshkent shahri', district: 'Chilonzor', address: 'Beshag\'och' },
    pricePerHour: 200000,
    currency: 'UZS',
    hasInstallment: true,
    amenities: commonAmenities,
    contact: { phone: ['+998711500000'] },
    workingHours: '08:00 - 22:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2023-05-01'
  },
  {
    id: 't5',
    name: 'Lokomotiv Volley',
    description: 'Professional voleybol maydonchasi. Jamoaviy o\'yinlar uchun ajoyib.',
    categories: ['volleyball'],
    images: ['https://loremflickr.com/800/600/volleyball?lock=13', 'https://loremflickr.com/800/600/net?lock=14', 'https://loremflickr.com/800/600/ball?lock=15'],
    rating: 4.5,
    reviewCount: 34,
    location: { lat: 41.2900, lng: 69.2800, region: 'Toshkent shahri', district: 'Mirobod', address: 'Temiryo\'lchilar ko\'chasi' },
    pricePerHour: 90000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998909008877'] },
    workingHours: '09:00 - 21:00',
    isOpenNow: false,
    reviews: [],
    createdAt: '2022-08-10'
  },
  {
    id: 't6',
    name: 'Neftchi Arena',
    description: 'Farg\'ona vodiysining eng zo\'r futbol maydonlaridan biri.',
    categories: ['football'],
    images: ['https://loremflickr.com/800/600/stadium?lock=16', 'https://loremflickr.com/800/600/soccer?lock=17', 'https://loremflickr.com/800/600/grass?lock=18'],
    rating: 4.7,
    reviewCount: 110,
    location: { lat: 40.3864, lng: 71.7864, region: 'Farg\'ona', district: 'Farg\'ona sh.', address: 'Murabbiylar ko\'chasi' },
    pricePerHour: 80000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998732001122'] },
    workingHours: '07:00 - 23:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2023-03-10'
  },

  // --- WATER SPORTS (Swimming, Rowing) ---
  {
    id: 'w1',
    name: 'Dolphin Aquapark & Pool',
    description: 'Yopiq va ochiq suzish havzalari, bolalar maydonchasi mavjud.',
    categories: ['swimming'],
    images: ['https://loremflickr.com/800/600/pool?lock=20', 'https://loremflickr.com/800/600/swimming?lock=21', 'https://loremflickr.com/800/600/water?lock=22'],
    rating: 4.5,
    reviewCount: 89,
    location: { lat: 41.3111, lng: 69.2797, region: 'Toshkent shahri', district: 'Yunusobod', address: 'Bodomzor yo\'li, 4' },
    pricePerHour: 60000,
    currency: 'UZS',
    hasInstallment: true,
    amenities: { ...commonAmenities, prayerRoom: false },
    contact: { phone: ['+998712000000'], instagram: 'dolphin_pool_uz' },
    workingHours: '07:00 - 22:00',
    isOpenNow: false,
    reviews: [],
    createdAt: '2021-05-10'
  },
  {
    id: 'w2',
    name: 'Suv Saroyi',
    description: 'Olimpiya zaxiralari suzish havzasi. 50 metrlik yo\'laklar.',
    categories: ['swimming'],
    images: ['https://loremflickr.com/800/600/swimming?lock=23', 'https://loremflickr.com/800/600/pool?lock=24', 'https://loremflickr.com/800/600/water?lock=25'],
    rating: 4.8,
    reviewCount: 150,
    location: { lat: 41.3200, lng: 69.2900, region: 'Toshkent shahri', district: 'Mirzo Ulug\'bek', address: 'Olimpiya shaharchasi' },
    pricePerHour: 70000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998712003344'] },
    workingHours: '06:00 - 21:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2022-01-20'
  },
  {
    id: 'w3',
    name: 'Eshkakchilar Bazasi (Tashkent Sea)',
    description: 'Professional eshkak eshish va baydarka sporti markazi.',
    categories: ['rowing'],
    images: ['https://loremflickr.com/800/600/rowing?lock=26', 'https://loremflickr.com/800/600/kayak?lock=27', 'https://loremflickr.com/800/600/lake?lock=28'],
    rating: 4.6,
    reviewCount: 40,
    location: { lat: 41.2500, lng: 69.3500, region: 'Toshkent viloyati', district: 'O\'rta Chirchiq', address: 'Tuybo\'g\'iz suv ombori' },
    pricePerHour: 50000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: { ...commonAmenities, lighting: false },
    contact: { phone: ['+998991112233'] },
    workingHours: '06:00 - 19:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2023-06-15'
  },
  {
    id: 'w4',
    name: 'Afrosiyob Pool',
    description: 'Samarqanddagi zamonaviy suzish majmuasi.',
    categories: ['swimming'],
    images: ['https://loremflickr.com/800/600/pool?lock=29', 'https://loremflickr.com/800/600/swim?lock=30', 'https://loremflickr.com/800/600/blue?lock=31'],
    rating: 4.4,
    reviewCount: 60,
    location: { lat: 39.6600, lng: 66.9600, region: 'Samarqand', district: 'Samarqand sh.', address: 'Universitet xiyoboni' },
    pricePerHour: 40000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998662334455'] },
    workingHours: '08:00 - 21:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2022-09-01'
  },
  {
    id: 'w5',
    name: 'Samarkand Rowing Canal',
    description: 'Xalqaro musobaqalar o\'tkaziladigan eshkak eshish kanali.',
    categories: ['rowing'],
    images: ['https://loremflickr.com/800/600/river?lock=32', 'https://loremflickr.com/800/600/boat?lock=33', 'https://loremflickr.com/800/600/race?lock=34'],
    rating: 4.9,
    reviewCount: 95,
    location: { lat: 39.6700, lng: 67.0000, region: 'Samarqand', district: 'Jomboy', address: 'Kanal bo\'yi' },
    pricePerHour: 60000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: { ...commonAmenities, lighting: true },
    contact: { phone: ['+998662225566'] },
    workingHours: '07:00 - 19:00',
    isOpenNow: false,
    reviews: [],
    createdAt: '2020-05-20'
  },

  // --- COMBAT SPORTS (Boxing, Judo, MMA, Taekwondo, Kurash) ---
  {
    id: 'c1',
    name: 'Chempion Boks Zali',
    description: 'Professional ringlar, boks qoplari va malakali murabbiylar.',
    categories: ['boxing'],
    images: ['https://loremflickr.com/800/600/boxing?lock=35', 'https://loremflickr.com/800/600/ring?lock=36', 'https://loremflickr.com/800/600/gloves?lock=37'],
    rating: 4.6,
    reviewCount: 32,
    location: { lat: 39.6542, lng: 66.9597, region: 'Samarqand', district: 'Samarqand sh.', address: 'Registon ko\'chasi' },
    pricePerHour: 30000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: { ...commonAmenities, parking: false },
    contact: { phone: ['+998933332211'] },
    workingHours: '06:00 - 22:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2022-03-15'
  },
  {
    id: 'c2',
    name: 'Buka Gym',
    description: 'MMA va Dzyudo bo\'yicha Toshkentdagi eng mashhur zal.',
    categories: ['mma', 'judo'],
    images: ['https://loremflickr.com/800/600/mma?lock=38', 'https://loremflickr.com/800/600/fighter?lock=39', 'https://loremflickr.com/800/600/gym?lock=40'],
    rating: 5.0,
    reviewCount: 210,
    location: { lat: 41.3000, lng: 69.2400, region: 'Toshkent shahri', district: 'Yakkasaroy', address: 'Nukus ko\'chasi' },
    pricePerHour: 50000,
    currency: 'UZS',
    hasInstallment: true,
    amenities: commonAmenities,
    contact: { phone: ['+998909998877'], instagram: 'bukagym' },
    workingHours: '07:00 - 23:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2021-11-01'
  },
  {
    id: 'c3',
    name: 'Milliy Kurash Markazi',
    description: 'O\'zbek milliy kurashini o\'rganish va shug\'ullanish uchun maxsus markaz.',
    categories: ['kurash'],
    images: ['https://loremflickr.com/800/600/wrestling?lock=41', 'https://loremflickr.com/800/600/sport?lock=42', 'https://loremflickr.com/800/600/hall?lock=43'],
    rating: 4.7,
    reviewCount: 45,
    location: { lat: 39.7700, lng: 64.4200, region: 'Buxoro', district: 'Buxoro sh.', address: 'Mustaqillik ko\'chasi' },
    pricePerHour: 20000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998652221100'] },
    workingHours: '08:00 - 20:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2022-06-10'
  },
  {
    id: 'c4',
    name: 'Taekwondo WTF Center',
    description: 'Bolalar va kattalar uchun Taekwondo mashg\'ulotlari.',
    categories: ['taekwondo'],
    images: ['https://loremflickr.com/800/600/taekwondo?lock=44', 'https://loremflickr.com/800/600/kick?lock=45', 'https://loremflickr.com/800/600/dojo?lock=46'],
    rating: 4.5,
    reviewCount: 67,
    location: { lat: 41.3400, lng: 69.2200, region: 'Toshkent shahri', district: 'Olmazor', address: 'Beruniy ko\'chasi' },
    pricePerHour: 35000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998971112233'] },
    workingHours: '09:00 - 21:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2023-02-01'
  },
  {
    id: 'c5',
    name: 'Gladiator Fight Club',
    description: 'Aralash jang san\'atlari (MMA) va krossfit zonasi.',
    categories: ['mma', 'boxing'],
    images: ['https://loremflickr.com/800/600/octagon?lock=47', 'https://loremflickr.com/800/600/fight?lock=48', 'https://loremflickr.com/800/600/training?lock=49'],
    rating: 4.8,
    reviewCount: 90,
    location: { lat: 40.8000, lng: 68.7000, region: 'Sirdaryo', district: 'Guliston', address: 'Xalqlar Do\'stligi' },
    pricePerHour: 25000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: { ...commonAmenities, shower: true },
    contact: { phone: ['+998672004455'] },
    workingHours: '10:00 - 22:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2022-12-12'
  },
  {
    id: 'c6',
    name: 'Ippon Judo Hall',
    description: 'Dzyudo bo\'yicha ixtisoslashgan sport majmuasi.',
    categories: ['judo'],
    images: ['https://loremflickr.com/800/600/judo?lock=50', 'https://loremflickr.com/800/600/tatami?lock=51', 'https://loremflickr.com/800/600/throw?lock=52'],
    rating: 4.6,
    reviewCount: 30,
    location: { lat: 41.5000, lng: 60.6000, region: 'Xorazm', district: 'Urganch', address: 'Al-Xorazmiy' },
    pricePerHour: 20000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998622223333'] },
    workingHours: '08:00 - 20:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2023-04-20'
  },

  // --- RACKET & GOLF (Tennis, Table Tennis, Badminton, Golf) ---
  {
    id: 'r1',
    name: 'NBU Tennis Club',
    description: 'Professional hard va grunt kortlar. Kechki yoritish tizimi.',
    categories: ['tennis'],
    images: ['https://loremflickr.com/800/600/tennis?lock=53', 'https://loremflickr.com/800/600/court?lock=54', 'https://loremflickr.com/800/600/racket?lock=55'],
    rating: 4.9,
    reviewCount: 150,
    location: { lat: 41.3300, lng: 69.2800, region: 'Toshkent shahri', district: 'Yunusobod', address: 'Amir Temur ko\'chasi' },
    pricePerHour: 100000,
    currency: 'UZS',
    hasInstallment: true,
    amenities: commonAmenities,
    contact: { phone: ['+998712345678'] },
    workingHours: '07:00 - 23:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2020-03-10'
  },
  {
    id: 'r2',
    name: 'Ping Pong Master',
    description: 'Stol tennisi ixlosmandlari uchun maxsus klub. Sifatli stollar.',
    categories: ['table_tennis'],
    images: ['https://loremflickr.com/800/600/pingpong?lock=56', 'https://loremflickr.com/800/600/tabletennis?lock=57', 'https://loremflickr.com/800/600/paddle?lock=58'],
    rating: 4.5,
    reviewCount: 44,
    location: { lat: 41.2800, lng: 69.2100, region: 'Toshkent shahri', district: 'Chilonzor', address: 'Qatortol' },
    pricePerHour: 40000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: { ...commonAmenities, shower: false },
    contact: { phone: ['+998901234455'] },
    workingHours: '09:00 - 22:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2022-08-05'
  },
  {
    id: 'r3',
    name: 'Badminton Center',
    description: 'Badminton federatsiyasi qoshidagi maxsus zal.',
    categories: ['badminton'],
    images: ['https://loremflickr.com/800/600/badminton?lock=59', 'https://loremflickr.com/800/600/shuttlecock?lock=60', 'https://loremflickr.com/800/600/indoor?lock=61'],
    rating: 4.7,
    reviewCount: 55,
    location: { lat: 41.3100, lng: 69.2600, region: 'Toshkent shahri', district: 'Shayxontohur', address: 'Navoiy ko\'chasi' },
    pricePerHour: 60000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998712445566'] },
    workingHours: '08:00 - 22:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2021-12-01'
  },
  {
    id: 'r4',
    name: 'Tashkent Lakeside Golf Club',
    description: 'O\'zbekistondagi yagona 18-teshikli professional golf maydoni.',
    categories: ['golf'],
    images: ['https://loremflickr.com/800/600/golf?lock=62', 'https://loremflickr.com/800/600/grass?lock=63', 'https://loremflickr.com/800/600/club?lock=64'],
    rating: 5.0,
    reviewCount: 88,
    location: { lat: 41.4000, lng: 69.4000, region: 'Toshkent viloyati', district: 'Qibray', address: 'Rohat ko\'li bo\'yi' },
    pricePerHour: 400000,
    currency: 'UZS',
    hasInstallment: true,
    amenities: commonAmenities,
    contact: { phone: ['+998998889900'] },
    workingHours: '08:00 - 18:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2018-05-15'
  },
  {
    id: 'r5',
    name: 'Dinamo Tennis Courts',
    description: 'Samarqand shahridagi ochiq tennis kortlari.',
    categories: ['tennis'],
    images: ['https://loremflickr.com/800/600/tennis?lock=65', 'https://loremflickr.com/800/600/court?lock=66', 'https://loremflickr.com/800/600/net?lock=67'],
    rating: 4.3,
    reviewCount: 30,
    location: { lat: 39.6500, lng: 66.9700, region: 'Samarqand', district: 'Samarqand sh.', address: 'Spitamen' },
    pricePerHour: 50000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998662211221'] },
    workingHours: '07:00 - 20:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2022-04-10'
  },

  // --- WINTER SPORTS (Skiing, Skating) ---
  {
    id: 'wi1',
    name: 'Amirsoy Resort Ski',
    description: 'Markaziy Osiyodagi eng zamonaviy tog\' chang\'i kurorti.',
    categories: ['skiing'],
    images: ['https://loremflickr.com/800/600/snow?lock=68', 'https://loremflickr.com/800/600/ski?lock=69', 'https://loremflickr.com/800/600/mountain?lock=70'],
    rating: 5.0,
    reviewCount: 500,
    location: { lat: 41.1600, lng: 69.8000, region: 'Toshkent viloyati', district: 'Bo\'stonliq', address: 'Amirsoy' },
    pricePerHour: 300000,
    currency: 'UZS',
    hasInstallment: true,
    amenities: commonAmenities,
    contact: { phone: ['+998711111111'], whatsapp: 'amirsoy' },
    workingHours: '09:00 - 20:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2019-12-01'
  },
  {
    id: 'wi2',
    name: 'Chimgan Ski Track',
    description: 'An\'anaviy va mashhur chang\'i uchish maskani.',
    categories: ['skiing'],
    images: ['https://loremflickr.com/800/600/skiing?lock=71', 'https://loremflickr.com/800/600/snowboard?lock=72', 'https://loremflickr.com/800/600/winter?lock=73'],
    rating: 4.6,
    reviewCount: 300,
    location: { lat: 41.5000, lng: 70.0000, region: 'Toshkent viloyati', district: 'Bo\'stonliq', address: 'Chimyon' },
    pricePerHour: 150000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: { ...commonAmenities, shower: false },
    contact: { phone: ['+998901112222'] },
    workingHours: '09:00 - 17:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2015-01-01'
  },
  {
    id: 'wi3',
    name: 'Humo Ice Dome',
    description: 'Yil davomida ishlaydigan professional muz saroyi.',
    categories: ['skating'],
    images: ['https://loremflickr.com/800/600/ice?lock=74', 'https://loremflickr.com/800/600/skate?lock=75', 'https://loremflickr.com/800/600/arena?lock=76'],
    rating: 4.9,
    reviewCount: 400,
    location: { lat: 41.3000, lng: 69.2500, region: 'Toshkent shahri', district: 'Chilonzor', address: 'Afrosiyob ko\'chasi' },
    pricePerHour: 80000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998712036666'] },
    workingHours: '11:00 - 23:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2019-03-15'
  },
  {
    id: 'wi4',
    name: 'Ice City',
    description: 'Ko\'ngilochar savdo markazi ichidagi muz maydoni.',
    categories: ['skating'],
    images: ['https://loremflickr.com/800/600/iceskating?lock=77', 'https://loremflickr.com/800/600/winter?lock=78', 'https://loremflickr.com/800/600/fun?lock=79'],
    rating: 4.4,
    reviewCount: 150,
    location: { lat: 41.2900, lng: 69.2200, region: 'Toshkent shahri', district: 'Yakkasaroy', address: 'Bobur ko\'chasi' },
    pricePerHour: 60000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998712050000'] },
    workingHours: '10:00 - 22:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2020-02-20'
  },
  {
    id: 'wi5',
    name: 'Beldersay Cableway',
    description: 'Uzun dor yo\'li va chang\'i trassalari.',
    categories: ['skiing'],
    images: ['https://loremflickr.com/800/600/cablecar?lock=80', 'https://loremflickr.com/800/600/mountain?lock=81', 'https://loremflickr.com/800/600/snow?lock=82'],
    rating: 4.5,
    reviewCount: 120,
    location: { lat: 41.4800, lng: 69.9500, region: 'Toshkent viloyati', district: 'Bo\'stonliq', address: 'Beldersoy' },
    pricePerHour: 100000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: { ...commonAmenities, shower: false },
    contact: { phone: ['+998903334444'] },
    workingHours: '09:00 - 16:30',
    isOpenNow: true,
    reviews: [],
    createdAt: '2016-12-10'
  },

  // --- EQUESTRIAN (Horse Riding) ---
  {
    id: 'e1',
    name: 'Jockey Club',
    description: 'Ot sporti va sayr qilish. Pony klub bolalar uchun.',
    categories: ['horse_riding'],
    images: ['https://loremflickr.com/800/600/horse?lock=83', 'https://loremflickr.com/800/600/equestrian?lock=84', 'https://loremflickr.com/800/600/riding?lock=85'],
    rating: 4.9,
    reviewCount: 45,
    location: { lat: 41.3500, lng: 69.3000, region: 'Toshkent viloyati', district: 'Bo\'stonliq', address: 'Chimyon yo\'li' },
    pricePerHour: 200000,
    currency: 'UZS',
    hasInstallment: true,
    amenities: { ...commonAmenities, shower: false, lighting: false },
    contact: { phone: ['+998998887766'], telegram: 'jockey_club' },
    workingHours: '09:00 - 18:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2019-08-20'
  },
  {
    id: 'e2',
    name: 'Universal Jumping Club',
    description: 'To\'siqlardan sakrash (Konkur) bo\'yicha mashg\'ulotlar.',
    categories: ['horse_riding'],
    images: ['https://loremflickr.com/800/600/horse?lock=86', 'https://loremflickr.com/800/600/jump?lock=87', 'https://loremflickr.com/800/600/stadium?lock=88'],
    rating: 4.8,
    reviewCount: 60,
    location: { lat: 41.2800, lng: 69.3300, region: 'Toshkent shahri', district: 'Yashnobod', address: 'Do\'stlik' },
    pricePerHour: 150000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998901235566'] },
    workingHours: '08:00 - 19:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2021-04-15'
  },
  {
    id: 'e3',
    name: 'Qorabayir Otchopar',
    description: 'Qashqadaryoning mashhur Qorabayir otlari bilan tanishish maskani.',
    categories: ['horse_riding'],
    images: ['https://loremflickr.com/800/600/horse?lock=89', 'https://loremflickr.com/800/600/field?lock=90', 'https://loremflickr.com/800/600/nature?lock=91'],
    rating: 4.7,
    reviewCount: 80,
    location: { lat: 38.8500, lng: 65.8000, region: 'Qashqadaryo', district: 'Qarshi', address: 'Otchopar mahallasi' },
    pricePerHour: 100000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: { ...commonAmenities, shower: false },
    contact: { phone: ['+998752223344'] },
    workingHours: '08:00 - 18:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2020-09-10'
  },
  {
    id: 'e4',
    name: 'Argamak Sherdor',
    description: 'Samarqanddagi ot sporti maktabi.',
    categories: ['horse_riding'],
    images: ['https://loremflickr.com/800/600/horse?lock=92', 'https://loremflickr.com/800/600/ride?lock=93', 'https://loremflickr.com/800/600/outdoor?lock=94'],
    rating: 4.6,
    reviewCount: 35,
    location: { lat: 39.6800, lng: 67.0500, region: 'Samarqand', district: 'Samarqand sh.', address: 'Cho\'pon ota' },
    pricePerHour: 120000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998662331122'] },
    workingHours: '09:00 - 18:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2022-03-01'
  },
  {
    id: 'e5',
    name: 'Vodiy Tulporlari',
    description: 'Andijon zotdor otlari klubi.',
    categories: ['horse_riding'],
    images: ['https://loremflickr.com/800/600/horse?lock=95', 'https://loremflickr.com/800/600/stable?lock=96', 'https://loremflickr.com/800/600/animal?lock=97'],
    rating: 4.8,
    reviewCount: 50,
    location: { lat: 40.7800, lng: 72.3500, region: 'Andijon', district: 'Asaka', address: 'Otchopar' },
    pricePerHour: 110000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998742223344'] },
    workingHours: '08:00 - 18:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2021-08-20'
  },

  // --- FITNESS (Gym, Crossfit) ---
  {
    id: 'f1',
    name: 'BeFit Pro',
    description: 'Eng zamonaviy trenajyorlar bilan jihozlangan premium fitnes klub.',
    categories: ['gym', 'crossfit'],
    images: ['https://loremflickr.com/800/600/gym?lock=98', 'https://loremflickr.com/800/600/fitness?lock=99', 'https://loremflickr.com/800/600/workout?lock=100'],
    rating: 5.0,
    reviewCount: 300,
    location: { lat: 41.3150, lng: 69.2500, region: 'Toshkent shahri', district: 'Shayxontohur', address: 'Oqtepa' },
    pricePerHour: 100000,
    currency: 'UZS',
    hasInstallment: true,
    amenities: commonAmenities,
    contact: { phone: ['+998711508888'], instagram: 'befit.uz' },
    workingHours: '06:00 - 23:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2020-01-10'
  },
  {
    id: 'f2',
    name: 'Chekhov Sport Club',
    description: 'Shahar markazidagi qulay joylashuv va malakali murabbiylar.',
    categories: ['gym'],
    images: ['https://loremflickr.com/800/600/gym?lock=101', 'https://loremflickr.com/800/600/dumbbells?lock=102', 'https://loremflickr.com/800/600/exercise?lock=103'],
    rating: 4.7,
    reviewCount: 180,
    location: { lat: 41.3000, lng: 69.2700, region: 'Toshkent shahri', district: 'Mirobod', address: 'Chexov ko\'chasi' },
    pricePerHour: 60000,
    currency: 'UZS',
    hasInstallment: true,
    amenities: commonAmenities,
    contact: { phone: ['+998712560000'] },
    workingHours: '07:00 - 23:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2019-05-05'
  },
  {
    id: 'f3',
    name: 'Power Gym Samarkand',
    description: 'Bodybuilding va pauerlifting uchun mo\'ljallangan zal.',
    categories: ['gym'],
    images: ['https://loremflickr.com/800/600/muscle?lock=104', 'https://loremflickr.com/800/600/gym?lock=105', 'https://loremflickr.com/800/600/weights?lock=106'],
    rating: 4.5,
    reviewCount: 70,
    location: { lat: 39.6600, lng: 66.9400, region: 'Samarqand', district: 'Samarqand sh.', address: 'Gagarin' },
    pricePerHour: 30000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998912223344'] },
    workingHours: '08:00 - 22:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2022-02-15'
  },
  {
    id: 'f4',
    name: 'Crossfit 998',
    description: 'Yuqori intensivlikdagi mashg\'ulotlar uchun maxsus zona.',
    categories: ['crossfit'],
    images: ['https://loremflickr.com/800/600/crossfit?lock=107', 'https://loremflickr.com/800/600/rope?lock=108', 'https://loremflickr.com/800/600/training?lock=109'],
    rating: 4.8,
    reviewCount: 90,
    location: { lat: 41.3400, lng: 69.2900, region: 'Toshkent shahri', district: 'Yunusobod', address: 'Bodomzor' },
    pricePerHour: 70000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998901110099'] },
    workingHours: '07:00 - 22:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2023-01-20'
  },
  {
    id: 'f5',
    name: 'Buxoro Fitnes',
    description: 'Ayollar va erkaklar uchun alohida zallar.',
    categories: ['gym'],
    images: ['https://loremflickr.com/800/600/treadmill?lock=110', 'https://loremflickr.com/800/600/gym?lock=111', 'https://loremflickr.com/800/600/yoga?lock=112'],
    rating: 4.6,
    reviewCount: 55,
    location: { lat: 39.7600, lng: 64.4100, region: 'Buxoro', district: 'Buxoro sh.', address: 'G\'ijduvon ko\'chasi' },
    pricePerHour: 35000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998652233445'] },
    workingHours: '08:00 - 21:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2021-09-10'
  },

  // --- SHOOTING (Archery, Guns) ---
  {
    id: 's1',
    name: 'Vatanparvar Shooting Range',
    description: 'Pnevmatik va o\'q otish qurollari uchun yopiq tir.',
    categories: ['shooting'],
    images: ['https://loremflickr.com/800/600/shooting?lock=113', 'https://loremflickr.com/800/600/target?lock=114', 'https://loremflickr.com/800/600/gun?lock=115'],
    rating: 4.5,
    reviewCount: 40,
    location: { lat: 41.2900, lng: 69.2400, region: 'Toshkent shahri', district: 'Yakkasaroy', address: 'Vatanparvar bog\'i' },
    pricePerHour: 50000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: { ...commonAmenities, shower: false },
    contact: { phone: ['+998712554433'] },
    workingHours: '10:00 - 20:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2022-05-01'
  },
  {
    id: 's2',
    name: 'Olympic Archery Range',
    description: 'Kamondan o\'q otish bo\'yicha professional mashg\'ulot maydoni.',
    categories: ['archery'],
    images: ['https://loremflickr.com/800/600/archery?lock=116', 'https://loremflickr.com/800/600/bow?lock=117', 'https://loremflickr.com/800/600/arrow?lock=118'],
    rating: 4.8,
    reviewCount: 60,
    location: { lat: 41.3500, lng: 69.3000, region: 'Toshkent shahri', district: 'Mirzo Ulug\'bek', address: 'TTZ mavzesi' },
    pricePerHour: 40000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998903332211'] },
    workingHours: '09:00 - 18:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2021-07-15'
  },
  {
    id: 's3',
    name: 'Snayper Club',
    description: 'Ko\'ngilochar o\'q otish markazi. Turli nishonlar mavjud.',
    categories: ['shooting'],
    images: ['https://loremflickr.com/800/600/range?lock=119', 'https://loremflickr.com/800/600/shooting?lock=120', 'https://loremflickr.com/800/600/target?lock=121'],
    rating: 4.4,
    reviewCount: 85,
    location: { lat: 41.3000, lng: 69.2000, region: 'Toshkent shahri', district: 'Chilonzor', address: 'Bunyodkor' },
    pricePerHour: 30000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: { ...commonAmenities, shower: false },
    contact: { phone: ['+998971112233'] },
    workingHours: '10:00 - 22:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2023-01-05'
  },
  {
    id: 's4',
    name: 'Yay Kamon',
    description: 'Milliy uslubdagi kamondan otish klubi.',
    categories: ['archery'],
    images: ['https://loremflickr.com/800/600/archery?lock=122', 'https://loremflickr.com/800/600/history?lock=123', 'https://loremflickr.com/800/600/wood?lock=124'],
    rating: 4.7,
    reviewCount: 30,
    location: { lat: 39.6500, lng: 66.9500, region: 'Samarqand', district: 'Samarqand sh.', address: 'Registon' },
    pricePerHour: 25000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998934445566'] },
    workingHours: '09:00 - 19:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2022-10-10'
  },
  {
    id: 's5',
    name: 'Dinamo Shooting',
    description: 'Ichki ishlar vazirligi sport jamiyati qoshidagi o\'q otish zali.',
    categories: ['shooting'],
    images: ['https://loremflickr.com/800/600/police?lock=125', 'https://loremflickr.com/800/600/training?lock=126', 'https://loremflickr.com/800/600/shooting?lock=127'],
    rating: 4.6,
    reviewCount: 45,
    location: { lat: 41.2800, lng: 69.2500, region: 'Toshkent shahri', district: 'Mirobod', address: 'Nukus' },
    pricePerHour: 45000,
    currency: 'UZS',
    hasInstallment: false,
    amenities: commonAmenities,
    contact: { phone: ['+998712334455'] },
    workingHours: '09:00 - 18:00',
    isOpenNow: true,
    reviews: [],
    createdAt: '2021-03-20'
  }
];
